name: 'SetupModLoader'
description: 'Setup the tModLoader environment for GitHub Actions.'
author: 'Chireiden'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'arrow-down-circle'  
  color: 'green'